baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Debate-Daily'
theme = 'mainroad'

# Needed To create the tags themselves 
[taxonomies]
  tag = "tags"
  category = "categories"

# Needed to avoid raw HTML printing and missing sidebar rendering
pygmentsCodeFences = true
pygmentsUseClasses = true
hasCJKLanguage = false
enableRobotsTXT = true
summaryLength = 30

[params]
  description = "An OS platform for exploring, sharing, and improving debate as a game."
  author = "Debate-Daily Team"
  customCSS = ["css/custom.css"] # Optional: If you want to customize styles

[Params.logo]
  title = "DebateDaily" # Logo title, otherwise will use site title
  subtitle = "The Home Of Better Debate" # Logo subtitle

  # Display site-wide social links
  showSocial = true
  showReadingTime = true
  showTags = true
  showBreadcrumbs = true
  showFooterCredits = true
  highlightColor = "#0080ff"

# Optional: Main menu if you want a header nav bar
[menu]

  [[menu.main]]
    name = "Contact: Email"
    url = "mailto:DebateDaily.App@gmail.com"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

   [[menu.main]]
    name = "Blog: 3NR Revamp Series"
    url = "/tags/3NR-Revamps/"
    weight = 3

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 4
    identifier = "tools"
    hasChildren = true

    [[menu.main]]
      parent = "tools"
      name = "Debate Tracker (BETA .87)"
      url = "/tools/debate-tracker"
      weight = 5

    [[menu.main]]
      parent = "tools"
      name = "DDQ (Daily Debate Question)"
      url = "/tools/ddq"
      weight = 6

    [[menu.main]]
      parent = "tools"
      name = "Round Timer (COMING SOON)"
      url = "/tools/timer"
      weight = 7

    [[menu.main]]
      parent = "tools"
      name = "Judge Paradigm Helper (COMING SOON)"
      url = "/tools/judge-helper"
      weight = 8