baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Debate-Daily'
theme = 'mainroad'

# Needed To create the tags themselves 
[taxonomies]
  tag = "tags"
  category = "categories"

# Needed to avoid raw HTML printing and missing sidebar rendering
pygmentsCodeFences = true
pygmentsUseClasses = true
hasCJKLanguage = false
enableRobotsTXT = true
summaryLength = 30

[params]
  description = "An OS platform for exploring, sharing, and improving debate as a game."
  author = "Debate-Daily Team"
  customCSS = ["css/custom.css"] # Optional: If you want to customize styles

[Params.logo]
  title = "DebateDaily" # Logo title, otherwise will use site title
  subtitle = "The Home Of Better Debate" # Logo subtitle

  # Display site-wide social links
  showSocial = true
  showReadingTime = true
  showTags = true
  showBreadcrumbs = true
  showFooterCredits = true
  highlightColor = "#0080ff"

# MAIN MENU BAR [Home // Tools // Blog: TTT // Blog 3NRs // PbT // Contact: Email ]

[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact: Email"
    url = "mailto:DebateDaily.App@gmail.com"
    weight = 10

[[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 2
    identifier = "tools"
    hasChildren = true

  [[menu.main]]
      parent = "tools"
      name = "Debate Tracker (BETA .87)"
      url = "/tools/debate-tracker"
      weight = 1

  [[menu.main]]
      parent = "tools"
      name = "DDQ (Daily Debate Question)"
      url = "/tools/ddq"
      weight = 2

  [[menu.main]]
      parent = "tools"
      name = "Round Timer (COMING SOON)"
      url = "/tools/timer"
      weight = 3

  [[menu.main]]
      parent = "tools"
      name = "Judge Paradigm Helper (COMING SOON)"
      url = "/tools/judge-helper"
      weight = 4

[[menu.main]]
    name = "Posts By Topic"
    url = "/tags/"
    weight = 5

[[menu.main]]
    name = "Blog: 3NR Revamps"
    url = "/tags/3nr-Revamps/"
    weight = 4

[[menu.main]]
    name = "Blog: Tuesday's Tool Tip"
    url = "/tags/Tool-Tips/"
    weight = 3
 
